global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'ai-processor'
  routes:
    - match:
        severity: critical
      receiver: 'ai-processor'
      continue: true
    - match:
        severity: warning
      receiver: 'ai-processor'

receivers:
  - name: 'ai-processor'
    webhook_configs:
      - url: 'http://ai_processor:8000/webhook/alertmanager'
        send_resolved: true
        max_alerts: 10

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
